//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament.Manager.SQLDataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitorPhaseInfo
    {
        public int IdCompetitionPhase { get; set; }
        public int IdCompetitor { get; set; }
        public string PhaseInfo { get; set; }
    
        public virtual CompetitionPhase CompetitionPhase { get; set; }
        public virtual Competitor Competitor { get; set; }
    }
}
