//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament.Manager.SQLDataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionPhase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompetitionPhase()
        {
            this.CompetitorPhaseInfoes = new HashSet<CompetitorPhaseInfo>();
            this.Matches = new HashSet<Match>();
        }
    
        public int Id { get; set; }
        public string Settings { get; set; }
        public int StageId { get; set; }
        public int IdCompetition { get; set; }
        public short CompetitionPhaseInfoType { get; set; }
        public string Name { get; set; }
    
        public virtual Competition Competition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompetitorPhaseInfo> CompetitorPhaseInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Match> Matches { get; set; }
    }
}
