//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament.Manager.SQLDataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int Id { get; set; }
        public int IdCompetitor1 { get; set; }
        public int IdCompetitor2 { get; set; }
        public int IdCompetition { get; set; }
        public string MatchInfo { get; set; }
    
        public virtual Competition Competition { get; set; }
        public virtual Competitor Competitor { get; set; }
        public virtual Competitor Competitor1 { get; set; }
    }
}
